/** Declaration file generated by dts-gen */

export = persistent_cache;

declare function persistent_cache(options: any): any;

declare namespace persistent_cache {
    const prototype: {
    };

}

